/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.1.1/samples
 */
plugins {
    application 
    id("com.github.johnrengelman.shadow") version "7.1.0"
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
}

repositories {
    mavenCentral() 
}

sourceSets {
    main {
        java {
            srcDir("src/main/java")
            include("**/*.java")
        }
        resources {
            srcDirs("src/main/resources")
        }
    }
}

dependencies {
    implementation("org.mariadb.jdbc:mariadb-java-client:2.7.4")
    implementation("org.json:json:20210307")
    implementation("org.springframework.boot:spring-boot-starter-data-rest")
}

application {
    mainClass.set("com.l2eminence.App") 
}

// Shadow task depends on Jar task, so these configs are reflected for Shadow as well
tasks.jar {
    manifest.attributes["Main-Class"] = "org.example.MainKt"
}