/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.1.1/samples
 */
plugins {
    application 
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
}

repositories {
    mavenCentral() 
}

dependencies {
    runtimeOnly("org.mariadb.jdbc:mariadb-java-client:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-data-rest")
    implementation("com.github.ben-manes.caffeine:caffeine:3.1.6") // https://mvnrepository.com/artifact/com.github.ben-manes.caffeine/caffeine
}
application {
    mainClass.set("com.l2eminence.App") 
}